---
apiVersion: v2
name: gitlab-ci-pipelines-exporter
version: 0.2.16
appVersion: v0.5.3
description: Prometheus / OpenMetrics exporter for GitLab CI pipelines insights
home: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
sources:
  - https://github.com/mvisonneau/helm-charts/tree/main/charts/gitlab-ci-pipelines-exporter
maintainers:
  - name: mvisonneau
    email: maxime.visonneau@gmail.com
dependencies:
  - name: redis
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    version: 16.4.0
    condition: redis.enabled
